### ISSUE TITLE
I think Reddint class is misspelled, should be Reddit

### ISSUE THREAD

**Issue by albemala** [dartoos-dev/flutter_brand_palettes#109]

**Comment by rafamizes** [comment]
Hello,

I'll fix it and let you know.

Cheers.

**Comment by albemala** [comment]
Thanks!

**Comment by rafamizes** [comment]
@albemala,

I fixed it.

The package version was set to 0.5.0.

Thanks for opening this issue.

**Comment by albemala** [comment]
fantastic, thank you @rafamizes !
